### ISSUE TITLE
Possible bug in graded exercise 2

### ISSUE THREAD

**Issue by hejops** [rattletat/homework-checker#5]
The third function is named `filter` in the template (which is shared with the python built-in), but it seems to cause test_11 to fail. Renaming the function to `filter_tokens` allowed the test to pass.

```
# >       self.assertEqual(submission.filter_tokens(tokens), cleaned)
# E       AttributeError: module 'submission' has no attribute 'filter_tokens'
# 
# tests.py:220: AttributeError
```

**Comment by rattletat** [comment]
Please use our communication channel for exercise-specific issues. That said, the exercise description already changed yesterday and your error message basically says that your submission lacks the function `filter_tokens` (formerly poorly translated as just `filter`).
